/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0.2/samples
 */
plugins {
    id("org.unbroken-dome.helm") version "1.6.1"
}

helm {
    downloadClient {
        enabled.set(true)
        version.set("3.6.0")
    }

    charts {
        val main by creating {
            chartVersion.set("0.1.0")
            sourceDir.set(file("src/main/helm"))
        }
    }
}